### ISSUE TITLE
Editable text field for course icon

### ISSUE THREAD

**Issue by adreier** [TheFridayInstitute/moodle-local_catalog#8]
Add an editable "text" field below the URL to the course icon image. It can always be the black text within a yellow rectangle, but it's going to be increasingly cumbersome to create new images with different text each time for eight courses this spring.

**Comment by mjsamberg** [comment]
Updates complete and pushed to staging site. Assigning to @adreier for testing.

**Comment by mjsamberg** [comment]
Acceptance and browser testing completed by @adreier. Moved to production.
